import type {Options} from '@docusaurus/plugin-content-docs';

// Alleen de navigatie krijgt leesbare namen; mappen en document-ID's blijven gelijk.
// De positie bepaalt de volgorde binnen de bovenliggende categorie.
const categories: Record<string, [label: string, position: number]> = {
  tooling: ['Ontwikkeltools', 1],
  'nodejs-+-typescript': ['Node.js en TypeScript', 2],
  frontend: ['Frontend met TypeScript', 2.5],
  'express.js': ['Express.js', 3],
  mysql: ['MySQL', 3.5],
  mongodb: ['MongoDB', 4],
  'full-stack': ['Full Stack', 4.5],
  security: ['Beveiliging', 5],
  exercises: ['Oefeningen', 6],
  labos: ["Labo's", 7],
  project: ['Project', 8],
  slides: ['Presentaties', 9],
  webframeworks: ['Webframeworks', 10],
  react: ['React', 11],
  nextjs: ['Next.js', 12],
  'react-native': ['React Native', 13],
  'nodejs-+-typescript/type-systeem': ['Typesysteem', 5],
  'nodejs-+-typescript/array-functions': ['Arraymethodes', 6],
  'nodejs-+-typescript/modules-npm': ['Modules en npm', 8],
  'nodejs-+-typescript/asynchroon-programmeren': ['Asynchroon programmeren', 10],
  'express.js/requests': ['HTTP-requests', 6],
  'express.js/cookies-en-sessions': ['Cookies, sessies en tokens', 13],
  'express.js/cookies-en-sessions/jwt-tokens': ['JSON Web Tokens (JWT)', 2],
  'express.js/authenticatie-en-autorisatie': ['Authenticatie en autorisatie', 14],
  'express.js/authenticatie-en-autorisatie/json-web-token-jwt': ['JWT-authenticatie', 2],
  'exercises/node-typescript': ['Node.js en TypeScript', 1],
  'exercises/frontend': ['Frontend met TypeScript', 1.5],
  'exercises/express': ['Express.js', 2],
  'exercises/mysql': ['MySQL', 2.5],
  'exercises/mongodb': ['MongoDB', 3],
  'exercises/full-stack': ['Full Stack', 3.5],
  'exercises/security': ['Beveiliging', 4],
  'exercises/herhaling': ['Herhalingsoefeningen', 5],
  'exercises/react': ['React', 6],
  'exercises/nextjs': ['Next.js', 7],
  'exercises/react-native': ['React Native', 8],
  'labos/webframeworks': ['Webframeworks', 26],
  'labos/labo1': ['Labo 1: Ontwikkeltools', 1],
  'labos/labo2': ['Labo 2: Basis van TypeScript', 2],
  'labos/labo3': ['Labo 3: Arrays', 3],
  'labos/labo4': ['Labo 4: Interfaces en functies', 4],
  'labos/labo4/interfaces': ['Interfaces', 1],
  'labos/labo4/functions': ['Functies', 2],
  'labos/labo5': ['Labo 5: Asynchroon programmeren en fetch', 5],
  'labos/labo6': ['Labo 6: Modules, npm en testen', 6],
  'labos/labo7': ['Labo 7: Express.js', 7],
  'labos/labo8': ['Labo 8: EJS en statische bestanden', 8],
  'labos/labo9': ['Labo 9: GET-requests', 9],
  'labos/labo10': ['Labo 10: POST-requests en testen', 10],
  'labos/labo11': ['Labo 11: Routers en middleware', 11],
  'labos/labo12': ['Labo 12: Herhaling van Express.js', 12],
  'labos/labo13': ['Labo 13: Basis van MongoDB', 13],
  'labos/14.-mongo-queries': ['Labo 14: MongoDB-query’s', 14],
  'labos/15.-mongo-+-express': ['Labo 15: MongoDB en Express.js', 15],
  'labos/16.-crud': ['Labo 16: CRUD', 16],
  'labos/17.-session-and-cookies': ['Labo 17: Sessies en cookies', 17],
  'labos/18.-session-based-login': ['Labo 18: Aanmelden met sessies', 18],
  'labos/19.-token-based-login': ['Labo 19: Aanmelden met tokens', 19],
  'labos/20.-testing': ['Labo 20: Testen', 20],
  'labos/21.-herhaling': ['Labo 21: Herhaling', 21],
  'labos/express-testen': ['Express.js testen', 22],
  'labos/extra': ['Extra oefeningen', 23],
  'labos/frontend-vite-en-dom': ['Frontend: Vite en DOM', 24],
  'labos/frontend-apis-en-dom': ['Frontend: API’s en DOM', 25],
  'project/semester-1': ['Semester 1', 3],
  'project/semester-2': ['Semester 2', 4],
  'slides/webontwikkeling': ['Webontwikkeling', 1],
};

const documents: Record<string, [label: string, position: number]> = {
  index: ['Introductie', 0],
  'nodejs-+-typescript/wat-is-nodejs': ['Wat is Node.js?', 1],
  'nodejs-+-typescript/waarom-typescript': ['Waarom TypeScript?', 2],
  'nodejs-+-typescript/projectmaken': ['Een nieuw project maken', 3],
  'nodejs-+-typescript/input-lezen': ['Invoer lezen', 4],
  'nodejs-+-typescript/type-systeem/basic-types': ['Basistypes', 1],
  'nodejs-+-typescript/type-systeem/arrays': ['Arrays', 2],
  'nodejs-+-typescript/type-systeem/interfaces': ['Interfaces', 3],
  'nodejs-+-typescript/type-systeem/classes': ['Classes', 4],
  'nodejs-+-typescript/type-systeem/functions': ['Functies', 5],
  'nodejs-+-typescript/array-functions/find': ['Array.find()', 4],
  'nodejs-+-typescript/exceptions': ['Foutafhandeling', 7],
  'nodejs-+-typescript/testing': ['Code testen', 9],
  'express.js/wat-is-een-backend-framework': ['Wat is een backendframework?', 1],
  'express.js/basis': ['Basis van Express.js', 2],
  'express.js/nodemon': ['Automatisch herstarten met nodemon', 3],
  'express.js/statische-bestanden': ['Statische bestanden', 4],
  'express.js/ejs': ['Templates met EJS', 5],
  'express.js/response': ['HTTP-responses', 7],
  'express.js/router': ['Routes organiseren', 8],
  'express.js/middleware': ['Middleware', 9],
  'express.js/client-side-typescript': ['TypeScript in de browser', 10],
  'express.js/deployment': ['Een toepassing publiceren', 11],
  'express.js/testen': ['Express.js testen', 12],
  'express.js/requests/get-request': ['GET-requests', 1],
  'express.js/requests/post-request': ['POST-requests', 2],
  'express.js/requests/multi-part-form-data': ['Bestanden uploaden met multipart/form-data', 3],
  'express.js/authenticatie-en-autorisatie/autorisatie-0auth': ['Autorisatie met OAuth', 1],
  'mongodb/wat-is-mongodb': ['Wat is MongoDB?', 1],
  'mysql/nodejs': ['MySQL in Node.js', 1],
  'mysql/gebruik-in-express': ['MySQL in Express.js', 2],
  'mysql/crud-api': ['CRUD met API-endpoints', 3],
  'full-stack/cors': ['CORS', 1],
  'full-stack/vite-planeten': ['Van form naar database', 2],
  'mongodb/mongodb-driver': ['De MongoDB-driver', 2],
  'mongodb/insert': ['Documenten toevoegen', 3],
  'mongodb/find': ['Documenten opzoeken', 4],
  'mongodb/limit-and-sort': ['Resultaten beperken en sorteren', 5],
  'mongodb/query-operators': ['Queryoperatoren', 6],
  'mongodb/update': ['Documenten wijzigen', 7],
  'mongodb/delete': ['Documenten verwijderen', 8],
  'mongodb/text-search': ['Zoeken in tekst', 9],
  'mongodb/gebruik-in-express.js': ['MongoDB gebruiken in Express.js', 10],
  'mongodb/CRUD': ['Een CRUD-toepassing bouwen', 11],
  'mongodb/mocking': ['Testen met mocks', 12],
  'security/environment-variables': ['Omgevingsvariabelen', 1],
  'security/cookies': ['Cookies', 2],
  'security/hashing': ['Hashing', 3],
  'security/sessions': ['Sessies', 4],
  'security/session-based-login': ['Aanmelden met sessies', 5],
  'project/algemeen': ['Algemene informatie', 1],
  'project/voorbereiding': ['Voorbereiding', 2],
  'slides/webontwikkeling/studiewijzer': ['Studiewijzer', 1],
  'slides/webontwikkeling/devcontainers': ['Devcontainers', 2],
  'slides/webontwikkeling/project': ['Projectvoorstelling', 3],
};

// Hergebruik de standaardgenerator zodat nieuwe documenten automatisch meekomen.
const sidebarItemsGenerator: NonNullable<Options['sidebarItemsGenerator']> = ({
  defaultSidebarItemsGenerator,
  ...args
}) => defaultSidebarItemsGenerator({
  ...args,
  categoriesMetadata: {
    ...args.categoriesMetadata,
    ...Object.fromEntries(Object.entries(categories).map(([directory, [label, position]]) => [
      directory,
      {...args.categoriesMetadata[directory], label, position},
    ])),
  },
  docs: args.docs.map((doc) => {
    const presentation = documents[doc.id];
    if (!presentation) return doc;
    const [label, position] = presentation;
    return {
      ...doc,
      sidebarPosition: position,
      frontMatter: {...doc.frontMatter, sidebar_label: label},
    };
  }),
});

export default sidebarItemsGenerator;
